name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  NODE_ENV: development

jobs:
  validate:
    name: Validate the changes
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout the code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: ğŸ“¦ Init Node, pnpm
        uses: ./.github/workflows/actions/init

      - name: âœ… Run validation
        run: pnpm run lint

      - name: âœ… Run build
        run: pnpm run build
